name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.13-ocaml-4.12-flambda'
          - 'coqorg/coq:8.12-ocaml-4.11-flambda'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-idt.opam'
          custom_image: ${{ matrix.image }}
